export const SET_INGREDIENTS = 'SET_INGREDIENTS'
export const INC_INGREDIENTS = 'INC_INGREDIENTS'
export const DEC_INGREDIENTS = 'DEC_INGREDIENTS'

export const TRY_SUBMIT = 'TRY_SUBMIT'
export const ORDER_SUBMIT_SUCCESS = 'ORDER_SUBMIT_SUCCESS'
export const ORDER_SUBMIT_FAILURE = 'ORDER_SUBMIT_FAILURE'
export const ORDER_PURCHASED = 'ORDER_PURCHASED'
export const FETCH_ORDER = 'FETCH_ORDER'


export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_END = 'AUTH_END'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'


export const CHECK_AUTH = 'CHECK_AUTH'